export const ROUTER_URL = {
  AUTH: {
    LOGIN: "/login",
    SIGN_UP: "/register",
    FORGOT_PASSWORD: "/forgot-password",
    RESET_PASSWORD: "/reset-password",
    VERIFY_EMAIL: "/verify-email",
    CONFIRM_EMAIL: "/confirm-email",
    UNAUTHOZIZED: "/unauthorized",
  },
  ADMIN: {
    BASE: "/admin",
    OVERVIEW: "/admin/overview",
    USERS: "/admin/users",
    SETTINGS: "/admin/settings",
    MANAGER_BLOG: "/admin/manager-blog",
    MANAGER_COURSE: "/admin/manager-course",
    MANAGER_USER: "/admin/manager-user",
    ANALYTICS: "/admin/analytics",
    STAFF_CONSULTANTS: "/admin/staff-consultants",
    MANAGERS: "/admin/managers",
    PERMISSIONS: "/admin/permissions",
    COMMUNITY_PROGRAMS: "/admin/community-programs",
    RESOURCES: "/admin/resources",
    ASSESSMENTS: "/admin/assessments",
    CONSULTATIONS: "/admin/consultations",
    EMERGENCY_SUPPORT: "/admin/emergency-support",
    ALERTS: "/admin/alerts",
    MESSAGES: "/admin/messages",
    SECURITY: "/admin/security",
    MANAGER_SESSION: "/admin/manager-course",
    MANAGER_LESSON: "/admin/manager-lesson",
    MANAGER_CATEGORY: "/admin/manager-category",
  },
  CONSULTANT: {
    BASE: "/consultant",
    OVERVIEW: "/consultant/tong-quan",
    USERS: "/consultant/khach-hang",
    SETTINGS: "/consultant/cai-dat",
    APPOINTMENTS: "/consultant/lich-hen-tu-van",
    CLIENTS: "/consultant/khach-hang",
    CONSULTATIONS: "/consultant/tuyen-dung",
    ASSESSMENTS: "/consultant/danh-gia",
    RESOURCES: "/consultant/tai-lieu",
    REPORTS: "/consultant/bao-cao",
  },
  STAFF: {
    BASE: "/staff",
    OVERVIEW: "/staff/overview",
    COURSES: "/staff/courses",
    CONTENT: "/staff/content",
    COMMUNITY_PROGRAMS: "/staff/community-programs",
    ASSESSMENTS: "/staff/assessments",
    EVENTS: "/staff/events",
    RESOURCES: "/staff/resources",
    USERS: "/staff/users",
    REPORTS: "/staff/reports",
    SETTINGS: "/staff/settings",
    PROFILE: "/staff/profile",
  },
  MANAGER: {
    BASE: "/manager",
    OVERVIEW: "/manager/tong-quan",
    ANALYTICS: "/manager/thong-ke",
    USERS: "/manager/khach-hang",
    STAFF: "/manager/nhan-vien",
    CONSULTANTS: "/manager/tu-van-vien",
    PROGRAMS: "/manager/chuong-trinh",
    SURVEYS: "/manager/khao-sat",
    COURSES: "/manager/khoa-hoc",
    REPORTS: "/manager/bao-cao",
    COMPLIANCE: "/manager/phap-luat",
    OPERATIONS: "/manager/hoat-dong",
    SCHEDULE: "/manager/lich-hen-tu-van",
    REVIEWS: "/manager/danh-gia",
    SETTINGS: "/manager/cai-dat",
  },
  CUSTOMER: {
    BASE: "/customer",
    APPOINTMENTS: "/customer/lich-hen-tu-van",
    FAVORITES: "/customer/favorites",
    SETTINGS: "/customer/settings",
    COURSE: "/customer/courses",
    ASSESSMENT: "/customer/assessment",
    MY_COURSE: "/customer/my-course",
    MY_COURSE_DETAIL: "/customer/my-course/:courseId",
    ORDER_HISTORY: "/customer/order",
    REVIEW_HISTORY: "/customer/review",
  },
  COMMON: {
    HOME: "/",
    ABOUT: "/about",
    CONTACT: "/contact",
    FAQ: "/faq",
    COVER: "/cover",
  },
  CLIENT: {
    BASE: "/",
    COURSE: "/courses",
    COURSE_DETAIL: "/courses/:courseId",
    BLOG: "/blog",
    BLOG_DETAIL: "/blog/:blogId",
    COUNSEL: "/counseling",
    PROGRAM: "/chuong-trinh-cong-dong",
    PROGRAM_DETAIL: "/chuong-trinh-cong-dong/:programId", // detail page
    SURVEY_DETAIL: "/survey/:surveyId", // client survey detail
    SURVEY_ATTEMPT: "/survey/:surveyId/attempt", // attempt quiz page
    SURVEY: "/survey", // client survey list
    ASSESSMENT: "/assessment",
    CART: "/cart",
    APPOINTMENTS: "/appointments",
    FAVORITES: "/favorites",
    SETTINGS: "/settings",
    PAYMENT: "/payment",
    PAYMENT_RESULT: "/payment-result",
  },
};
