export const ROUTER_URL = {
  AUTH: {
    LOGIN: "/login",
    SIGN_UP: "/register",
    FORGOT_PASSWORD: "/forgot-password",
    RESET_PASSWORD: "/reset-password",
    VERIFY_EMAIL: "/verify-email",
    CONFIRM_EMAIL: "/confirm-email",
    UNAUTHOZIZED: "/unauthorized",
  },
  ADMIN: {
    BASE: "/admin",
    OVERVIEW: "/admin/overview",
    USERS: "/admin/users",
    SETTINGS: "/admin/settings",
    MANAGER_BLOG: "/admin/manager-blog",
    MANAGER_COURSE: "/admin/manager-course",
    MANAGER_USER: "/admin/manager-user",
    ANALYTICS: "/admin/analytics",
    STAFF_CONSULTANTS: "/admin/staff-consultants",
    MANAGERS: "/admin/managers",
    PERMISSIONS: "/admin/permissions",
    COMMUNITY_PROGRAMS: "/admin/community-programs",
    RESOURCES: "/admin/resources",
    ASSESSMENTS: "/admin/assessments",
    CONSULTATIONS: "/admin/consultations",
    EMERGENCY_SUPPORT: "/admin/emergency-support",
    ALERTS: "/admin/alerts",
    MESSAGES: "/admin/messages",
    SECURITY: "/admin/security",
  },
  CONSULTANT: {
    BASE: "/consultant",
    OVERVIEW: "/consultant/overview",
    USERS: "/consultant/users",
    SETTINGS: "/consultant/settings",
    APPOINTMENTS: "/consultant/appointments",
    CLIENTS: "/consultant/clients",
    CONSULTATIONS: "/consultant/consultations",
    ASSESSMENTS: "/consultant/assessments",
    RESOURCES: "/consultant/resources",
    REPORTS: "/consultant/reports",
  },
  STAFF: {
    BASE: "/staff",
    OVERVIEW: "/staff/overview",
    COURSES: "/staff/courses",
    CONTENT: "/staff/content",
    COMMUNITY_PROGRAMS: "/staff/community-programs",
    ASSESSMENTS: "/staff/assessments",
    EVENTS: "/staff/events",
    RESOURCES: "/staff/resources",
    USERS: "/staff/users",
    REPORTS: "/staff/reports",
    SETTINGS: "/staff/settings",
    PROFILE: "/staff/profile",
  },
  MANAGER: {
    BASE: "/manager",
    OVERVIEW: "/manager/overview",
    ANALYTICS: "/manager/analytics",
    STAFF: "/manager/staff",
    CONSULTANTS: "/manager/consultants",
    PROGRAMS: "/manager/programs",
    COURSES: "/manager/courses",
    REPORTS: "/manager/reports",
    COMPLIANCE: "/manager/compliance",
    OPERATIONS: "/manager/operations",
    SCHEDULE: "/manager/schedule",
    REVIEWS: "/manager/reviews",
    SETTINGS: "/manager/settings",
  },
  CUSTOMER: {
    BASE: "/customer",
    APPOINTMENTS: "/customer/appointments",
    FAVORITES: "/customer/favorites",
    SETTINGS: "/customer/settings",
    COURSE: "/customer/courses",
    ASSESSMENT: "/customer/assessment",
  },
  COMMON: {
    HOME: "/",
    ABOUT: "/about",
    CONTACT: "/contact",
    FAQ: "/faq",
    COVER: "/cover",
  },
  CLIENT: {
    BASE: "/",
    COURSE: "/courses",
    COURSE_DETAIL: "/courses/:courseId",
    BLOG: "/blog",
    BLOG_DETAIL: "/blog/:blogId",
    COUNSEL: "/counseling",
    COMMUNITY: "/community",
    ASSESSMENT: "/assessment",
    CART: "/cart",
    APPOINTMENTS: "/appointments",
    FAVORITES: "/favorites",
    SETTINGS: "/settings",
  }
};
